### ISSUE TITLE
Still compatible with TEC?

### ISSUE THREAD

**Issue by karks88** [mt-support/tribe-ext-default-ticket-fieldset#3]
When trying to update a staging site to The Events Calendar to 6.0.11, I received a critical WP error:

An error of type E_ERROR was caused in line 332 of the file /privatefolders/wp-content/plugins/tec-labs-default-attendee-fields-main/src/Tec/Settings.php. Error message: Uncaught Error: Class 'Tribe__Tickets_Plus__Meta__Fieldset' not found in /privatefolders/wp-content/plugins/tec-labs-default-attendee-fields-main/src/Tec/Settings.php:332
Stack trace:
#0 /privatefolders/wp-content/plugins/tec-labs-default-attendee-fields-main/src/Tec/Settings.php(206): Tribe\Extensions\Default_Ticket_Fieldset\Settings->get_ticket_fieldsets()
#1 /privatefolders/wp-includes/class-wp-hook.php(308): Tribe\Extensions\Default_Ticket_Fieldset\Settings->add_settings()
#2 /privatefolders/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#3 /privatefolders/wp-includes/plugin.php(517): WP_Hook->do_action()
#4 /privatefolders/wp-admin/admin.php(175): do_action()
#5 /privatefolders/wp-admin/update.php

**Comment by andrasguseo** [comment]
Yes, it's still compatible. Are you still getting that fatal? If yes, how can I reproduce it?
